#!/bin/bash
node="$(which node)"
pidfile="pm2-ant.pid"
prefixINFO="\033[1;32m[INFO]\033[0m"
prefixWARN="\033[1;33m[WARNING]\033[0m"

function isRunning() {
  if [ ! -f $pidfile ]
    then
      return 0;
  fi
  if [ ! -s $pidfile ]
    then 
      rm $pidfile;
      return 0;
  fi
  if test $(ps -p $(cat $pidfile) | wc -l) -gt 1
    then 
      return 1;
  fi 
  rm $pidfile;
  return 0;
}

function status() {
  isRunning;
  if [ 0 -eq $? ];
    then
      echo -e "$prefixWARN \033[31m✘ stopped\033[0m";
    else
      echo -e "$prefixINFO \033[32m✔ running\033[0m";
  fi
}

case "$1" in
  start)
    isRunning;
    if [ 0 -eq $? ]
      then
        echo -e "$prefixINFO Starting..."
        $node ./lib/daemon "$@"
        sleep 1;
    fi
    status;
    ;;

  stop)
    isRunning;
    if [ 0 -eq $? ]
      then
        echo -e "$prefixWARN Already stopped.";
      else
        echo -e "$prefixINFO Stopping..."
        kill $(cat $pidfile);
        sleep 1;
        status;
    fi
    ;;

  restart)
    isRunning;
    if [ 0 -eq $? ];
      then
        echo -e "$prefixWARN PID not found, no need to stop anything.";
        $node ./lib/daemon "$@"
      else
        kill -SIGHUP $(cat $pidfile);
    fi
    status;
    ;;

  status)
    status;
    ;;

  *)
    echo -e "Usage: {start|stop|restart}\n"
    exit 1
esac